services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10.10"
    ports:
      - "8095:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # gradio:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       PYTHON_VERSION: "3.10.10"
  #   ports:
  #     - "7860:7860"
  #   command: ["python", "gradio_demo.py"]
  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: 1
  #           capabilities: [gpu]
