services:
  server:
    build:
      context: .
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - cache-volume:/cache
    environment:
      - TRANSFORMERS_CACHE=/cache

volumes:
  cache-volume:
